name: app1
namespace: alpha
deploy:
  spec:
    replicaCount: 1
  image: "/app1:1ac19dc3a43de29349fc63e7b522f344cc172249"
  template:
    spec:
      containers:
        resources:
          limits:
            cpu: 300m
            memory: 600Mi
          requests:
            cpu: 200m
            memory: 300Mi
hpa:
  spec:
    minReplicas: 1
    maxReplicas: 10
    metrics:
      averageUtilization: 85
service:
  type: ClusterIP
  port: 8080
