name: app1
namespace: production
deploy:
  spec:
    replicaCount: 1
  image: 636834414377.dkr.ecr.eu-west-1.amazonaws.com/app1:55350a6c6579e36945c3d8d6ef65e85cd9759a8a
  template:
    spec:
      containers:
        resources:
          limits:
            cpu: 300m
            memory: 600Mi
          requests:
            cpu: 200m
            memory: 300Mi
hpa:
  spec:
    minReplicas: 1
    maxReplicas: 10
    metrics:
      averageUtilization: 85
service:
  type: ClusterIP
  port: 8080
