name: app1
namespace: alpha
deploy:
  spec:
    replicaCount: 1
  image: "/app1:742a8d49b654d73912b69b6e76885b548fd6d458"
  template:
    spec:
      containers:
        resources:
          limits:
            cpu: 300m
            memory: 600Mi
          requests:
            cpu: 200m
            memory: 300Mi
hpa:
  spec:
    minReplicas: 1
    maxReplicas: 10
    metrics:
      averageUtilization: 85
service:
  type: ClusterIP
  port: 8080
