name: nest-js-github-actions-monorepo
namespace: alpha
deploy:
  spec:
    replicaCount: 1
  image: 636834414377.dkr.ecr.eu-west-1.amazonaws.com/nest-js-github-actions-monorepo:c019cf7410a8cc44941e0d525e0d13c7d829d52a
  template:
    spec:
      containers:
        resources:
          limits:
            cpu: 300m
            memory: 600Mi
          requests:
            cpu: 200m
            memory: 300Mi
hpa:
  spec:
    minReplicas: 1
    maxReplicas: 10
    metrics:
      averageUtilization: 85
service:
  type: ClusterIP
  port: 8080
