name: nest-js-github-actions-monorepo
namespace: production
deploy:
  spec:
    replicaCount: 1
  image: 636834414377.dkr.ecr.eu-west-1.amazonaws.com/nest-js-github-actions-monorepo:87a05ee84249f43e065eb1a12cb1e7fd79348870
  template:
    spec:
      containers:
        resources:
          limits:
            cpu: 300m
            memory: 600Mi
          requests:
            cpu: 200m
            memory: 300Mi
hpa:
  spec:
    minReplicas: 1
    maxReplicas: 10
    metrics:
      averageUtilization: 85
service:
  type: ClusterIP
  port: 8080
