name: nest-js-github-actions-monorepo
namespace: alpha
deploy:
  spec:
    replicaCount: 1
  image: 636834414377.dkr.ecr.eu-west-1.amazonaws.com/nest-js-github-actions-monorepo:f64fea8f1b5b177429b2e90d4f47c91d42fc5cb9
  template:
    spec:
      containers:
        resources:
          limits:
            cpu: 300m
            memory: 600Mi
          requests:
            cpu: 200m
            memory: 300Mi
hpa:
  spec:
    minReplicas: 1
    maxReplicas: 10
    metrics:
      averageUtilization: 85
service:
  type: ClusterIP
  port: 8080
